### ISSUE TITLE
Cannot set config options

### ISSUE THREAD

**Issue by Llammissar** [s417-lama/plotly_ex#2]
Plotly has a fourth argument to newChart that isn't currently supported for setting configurations like `responsive: true` and `displayModeBar: false` (I tried calling `PlotlyEx.plot` with a config map on the off chance it just wasn't documented, but no love.)

**Comment by s417-lama** [comment]
Thank you for reporting it! (I didn't know `config` parameter. It seems to be useful.)

Config arg was added in 134219117848339cb2ec734fc0d561b6efedd311. Close.
